name: Rust

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  x86:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Run tests without SIMD
      run: cargo test --verbose -- byte_order --nocapture

  wasm:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: wasm32-wasi

    - name: Install wasmtime
      run: |
        curl https://wasmtime.dev/install.sh -sSf | bash
        echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

    - name: Run tests without SIMD
      run: cargo test --target wasm32-wasi --verbose -- byte_order --nocapture

  aarch64:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: aarch64-unknown-linux-gnu

    - name: Install cross
      run: cargo install cross

    - name: Run tests without SIMD
      run: cross test --target aarch64-unknown-linux-gnu --verbose -- byte_order --nocapture

    - name: Rust tests on PowerPC (big endian)
      run: cross test --target powerpc-unknown-linux-gnu -- byte_order --nocapture
